# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScanItems' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScanItems
    pod 'Moya/RxSwift'
    pod 'RxCocoa'
    pod 'RxSwift'
    pod 'SVProgressHUD'
    pod 'RxDataSources'
    pod 'SDWebImage'
    pod 'SwiftIconFont'

  target 'ScanItemsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'RxTest'
  end

end
